#--> 에러발생
f=open("나없는파일",'r')
